### ISSUE TITLE
Training code of NLNet

### ISSUE THREAD

**Issue by DanChen001** [cig-skoltech/NLNet#1]
Hi, Dr. Lefkimmiatis,

Thank you for sharing the code.

Could you share the training code?  Thanks.

**Comment by cig-skoltech** [comment]
For the training code you can refer to the UDNet package which is an extension of the NLNet network.

**Comment by arscarrot** [comment]
Hi, I have a problem when I run nlnet_denoise_demo.m.
![image](https://user-images.githubusercontent.com/31820093/54502851-a201d900-4967-11e9-8a61-93992b8ce6b8.png)
the function 'nn_pad' cannot find..THANKS.

**Comment by cig-skoltech** [comment]
Unfortunately, the error that you report is not detailed enough to be able to assist you. The function nn_pad exists in the subfolder matlab/custom_layers
